;;;; stumpwm-settings.lisp

(in-package #:stumpwm-settings)

(handler-bind ((defconfig:database-already-exists-error
                 (lambda (c)
                   (let ((r (find-restart 'defconfig::continue c)))
                     (when r
                       (invoke-restart r))))))
  (defconfig:define-defconfig-db *stumpwm-db* :stumpwm
    :doc "defconfig database for stumpwm"))

(defmacro defsetting (place &rest keys)
  `(defconfig:define-variable-config ,place ,place
     :db *stumpwm-db*
     :regen-config t
     ,@keys))

(defmacro with-typespec (typespec &body variables)
  (let ((forms (loop for variable in variables
                     collect `(defsetting ,variable :typespec ,typespec))))
    `(progn ,@forms)))

(defvar *customized-settings* nil)

(defun customize (symbol value)
  (let* ((config-info (car (defconfig:search-configurable-objects symbol
                                                                  :stumpwm)))
         (validated? (and config-info
                          (funcall (defconfig:config-info-predicate config-info)
                                   value))))
    (if validated?
        (progn (stumpwm:call-in-main-thread
                (lambda ()
                  (setf (symbol-value symbol) value)))
               ;; (push symbol *customized-settings*)
               :valid)
        :invalid)))

(defun reset (symbol)
  (stumpwm:call-in-main-thread
   (lambda ()
     (defconfig:reset-computed-place symbol :db (defconfig:get-db :stumpwm)))))

(defun generate-set-string (symbol)
  (let ((value (symbol-value symbol)))
    (if (eq t value)
        (format nil "T")
        (typecase value
          (string (format nil "~S" value))
          (number value)
          (null "NIL")
          (keyword (format nil ":~A" value))
          (symbol (format nil "'~A" value))
          (cons (format nil "'~S" value))))))

(defun gen-final (place list)
  (cond ((eql place 'stumpwm:*colors*)
         (cons (format nil "(update-color-map (current-screen))") list))
        (t list)))

(defun write-settings-to-file ()
  (let ((finalized nil))
    (with-open-file (file "~/.stumpwm.d/customize-variables.lisp"
                          :direction :output
                          :element-type 'character
                          :if-exists :supersede
                          :if-does-not-exist :create)
      (format file ";;;; This file, customize-variables.lisp, was generated by the package~%;;;; stumpwm-settings, and should not be edited. If you edit it by hand,~%;;;; your changes may be overwritten by stumpwm-settings.~%~%")
      (format file "(in-package :stumpwm)~%~%(unless (find-package :stumpwm-settings)~%  (ql:quickload :stumpwm-settings))~%~%(in-package :stumpwm-settings)~%~%(defconfig:setv~%")
      (loop for setting being the hash-value of (cdr stumpwm-settings::*stumpwm-db*)
            for place = (defconfig:config-info-place setting)
            unless (equal (symbol-value place)
                          (defconfig:config-info-default-value setting))
              do (format file "~& ~A ~A~&"
                         place (generate-set-string place))
                 (setf finalized (gen-final place finalized)))
      (format file " :db stumpwm-settings:*stumpwm-db*)~%")
      (loop for final in finalized
          do (format file "~%~A~&" final)))))
